import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import Header from "@/components/layout/Header";
import {ThemeProvider} from "@/components/theme-provider";
import Footer from "@/components/layout/Footer";


const RobotoFont = Roboto({

    variable: "--font-roboto",
    subsets:['latin']

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${RobotoFont.className} font overflow-hidden  antialiased`}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
      <MainLayout>
        {children}
      </MainLayout>
      </ThemeProvider>
      </body>
    </html>
  );
}
